# -*- coding: utf-8 -*-
"""SMA+practical 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qahxf-X75S3M5eE4orytK-3AGwOCyPsH
"""

import requests

video_id = "IJDHEG5sEV0"
api_key = "AIzaSyAqi1jTnCbKEh3SQZu_7iHIDfhvI9w19oM"

# Retrieve video information
video_info_url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}"
video_info_response = requests.get(video_info_url)
video_info_data = video_info_response.json()
video_info_data

# Retrieve video comments
comments_url = f"https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId={video_id}&key={api_key}"
comments_response = requests.get(comments_url)
comments_data = comments_response.json()
comments_data

# Extract the comments
comments = [item["snippet"]["topLevelComment"]["snippet"]["textOriginal"] for item in comments_data["items"]]
print(comments)

from textblob import TextBlob

def get_comment_sentiment(comment):
    analysis = TextBlob(comment)
    if analysis.sentiment.polarity > 0:
        return "Positive"
    elif analysis.sentiment.polarity == 0:
        return "Neutral"
    else:
        return "Negative"

comment_list = []
sentiment_list = []

for comment in comments:
    sentiment = get_comment_sentiment(comment)
    comment_list.append(comment)
    sentiment_list.append(sentiment)
    print(f"{comment} : {sentiment}")

import pandas as pd

sentiment_df = pd.DataFrame({"Comments": comment_list, "Sentiment": sentiment_list})
sentiment_df.head()
sentiment_df.to_csv("YouTube_Comments_Sentiment.csv")

import seaborn as sns
import matplotlib.pyplot as plt

# Load the sentiment DataFrame from the CSV file
sentiment_df = pd.read_csv("YouTube_Comments_Sentiment.csv")

# Count the number of comments in each sentiment category
sentiment_counts = sentiment_df["Sentiment"].value_counts()

# Create a bar plot
plt.figure(figsize=(8, 6))
sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, palette="viridis")
plt.title("Distribution of Sentiments in YouTube Comments")
plt.xlabel("Sentiment")
plt.ylabel("Number of Comments")
plt.show()